@host = http://localhost:3000
@route = gigs
@url = {{host}}/{{route}}
@contentType = application/json

### route GET /gigs
### desc  Get all gigs
GET {{url}}


### route POST /gigs
### desc  Add gig to DB
POST {{url}}
Content-Type: {{contentType}}

{
  "title": "another Test gig",
  "technologies": "javascript, express, ejs, sequelize",
  "description": "This is a another test",
  "budget": "500",
  "contact_email": "anothertest@test.com"
}

###
POST {{url}}
Content-Type: {{contentType}}

{
  "title": "Wordpress Site",
  "technologies": "PHP, HTML, CSS",
  "description": "Build a simple wordpress site",
  "budget": "1000",
  "contact_email": "wordpressdev@test.com"
}